project_id = "abieqpmvsufqzbqirqnu"

[functions.admin-check]
verify_jwt = false

[functions.admin-signup]
verify_jwt = false

[functions.auth-settings]
verify_jwt = false

[functions.aviasales-click]
verify_jwt = false

[functions.aviasales-search]
verify_jwt = false

[functions.ratehawk-autocomplete]
verify_jwt = false

[functions.ratehawk-book]
verify_jwt = false

[functions.ratehawk-check-booking]
verify_jwt = false

[functions.ratehawk-client]
verify_jwt = false

[functions.ratehawk-hotel]
verify_jwt = false

[functions.ratehawk-prebook]
verify_jwt = false

[functions.ratehawk-search]
verify_jwt = false

[functions.ratehawk-test-multicomplete]
verify_jwt = false